package dnsmasq

import (
	"context"
	"fmt"
	"log/slog"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/tensordriftstudio/redwolf/internal/domain"
	"github.com/tensordriftstudio/redwolf/internal/port"
)

var _ port.DNSMasqManager = (*Manager)(nil)

// Config defines the runtime configuration parameters for dnsmasq.
type Config struct {
	Interface            string
	HTTPPort             int
	ServerIP             string
	TFTPDir              string
	ConfDir              string
	LogDir               string
	SubnetCIDR           string
	DHCPRangeStart       string
	DHCPRangeEnd         string
	Gateway              string
	DNSServers           []string
	LeaseDurationMinutes int
	ProxyDHCP            bool
}

// Manager supervises the dnsmasq child process.
type Manager struct {
	cfg     Config
	mu      sync.Mutex
	cmd     *exec.Cmd
	running bool
	cancel  context.CancelFunc
	exitCh  chan struct{}
}

// NewManager creates a dnsmasq process manager.
func NewManager(cfg Config) *Manager {
	if cfg.Interface == "" {
		cfg.Interface = "eth0"
	}
	if cfg.HTTPPort == 0 {
		cfg.HTTPPort = 8080
	}
	if cfg.TFTPDir == "" {
		cfg.TFTPDir = "/var/lib/redwolf/tftp"
	}
	if cfg.ConfDir == "" {
		cfg.ConfDir = "/etc/redwolf"
	}
	if cfg.LogDir == "" {
		cfg.LogDir = "/var/log/redwolf"
	}

	return &Manager{cfg: cfg}
}

// RenderConfig generates the active dnsmasq configuration file.
func (m *Manager) RenderConfig(ctx context.Context) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	if err := os.MkdirAll(m.cfg.ConfDir, 0755); err != nil {
		return fmt.Errorf("failed to create config dir: %w", err)
	}
	if err := os.MkdirAll(m.cfg.LogDir, 0755); err != nil {
		return fmt.Errorf("failed to create log dir: %w", err)
	}
	if err := os.MkdirAll(m.cfg.TFTPDir, 0755); err != nil {
		return fmt.Errorf("failed to create tftp dir: %w", err)
	}
	m.seedTFTPBootloaders(ctx)

	serverIP := m.cfg.ServerIP
	if serverIP == "" {
		serverIP = m.detectInterfaceIP(m.cfg.Interface)
		if serverIP == "" {
			serverIP = "127.0.0.1"
		}
	}

	// Calculate Netmask from SubnetCIDR
	netmask := "255.255.255.0"
	if m.cfg.SubnetCIDR != "" {
		if _, ipNet, err := net.ParseCIDR(m.cfg.SubnetCIDR); err == nil && len(ipNet.Mask) == 4 {
			netmask = fmt.Sprintf("%d.%d.%d.%d", ipNet.Mask[0], ipNet.Mask[1], ipNet.Mask[2], ipNet.Mask[3])
		}
	}

	leaseStr := "12h"
	if m.cfg.LeaseDurationMinutes > 0 {
		leaseStr = fmt.Sprintf("%dm", m.cfg.LeaseDurationMinutes)
	}

	var dhcpRangeSection string
	if m.cfg.ProxyDHCP {
		dhcpRangeSection = fmt.Sprintf("# ProxyDHCP Mode (upstream DHCP allocates IP addresses)\ndhcp-range=%s,proxy\n", serverIP)
	} else if m.cfg.DHCPRangeStart != "" && m.cfg.DHCPRangeEnd != "" {
		var routerOpt string
		if m.cfg.Gateway != "" {
			routerOpt = fmt.Sprintf("dhcp-option=tag:redwolf,option:router,%s\n", m.cfg.Gateway)
		}
		var dnsOpt string
		if len(m.cfg.DNSServers) > 0 {
			dnsOpt = fmt.Sprintf("dhcp-option=tag:redwolf,option:dns-server,%s\n", strings.Join(m.cfg.DNSServers, ","))
		}

		dhcpRangeSection = fmt.Sprintf(`# Authoritative DHCP Pool
dhcp-authoritative
dhcp-range=set:redwolf,%s,%s,%s,%s
%s%s`,
			m.cfg.DHCPRangeStart, m.cfg.DHCPRangeEnd, netmask, leaseStr,
			routerOpt, dnsOpt,
		)
	} else {
		// Fallback to ProxyDHCP mode based on server IP so PXE boot options are still served
		dhcpRangeSection = fmt.Sprintf("# Default ProxyDHCP Mode (auto-detected interface)\ndhcp-range=%s,proxy\n", serverIP)
	}

	arm64BootLine := "# dhcp-boot=tag:!ipxe,tag:arm64,ipxe-arm64.efi (arm64 binary not present in tftp root)"
	if _, err := os.Stat(filepath.Join(m.cfg.TFTPDir, "ipxe-arm64.efi")); err == nil {
		arm64BootLine = "dhcp-boot=tag:!ipxe,tag:arm64,ipxe-arm64.efi"
	} else {
		slog.DebugContext(ctx, "ipxe-arm64.efi not present in tftp root; arm64 pxe boot disabled until binary is provided", "tftp_dir", m.cfg.TFTPDir)
	}

	confContent := fmt.Sprintf(`# Auto-generated by RedWolf Core Engine - %s
port=0
interface=%s
bind-dynamic

%s
# Client System Architecture matching (Option 93)
dhcp-match=set:bios,option:client-arch,0
dhcp-match=set:efi64,option:client-arch,7
dhcp-match=set:efi64,option:client-arch,9
dhcp-match=set:arm64,option:client-arch,11
dhcp-match=set:ipxe,77,"iPXE"

# Serve initial architecture-specific bootstrap loaders
dhcp-boot=tag:!ipxe,tag:bios,undionly.kpxe
dhcp-boot=tag:!ipxe,tag:efi64,ipxe.efi
%s

# Dynamic MAC-aware iPXE chainloader endpoint
dhcp-boot=tag:ipxe,http://%s:%d/boot.ipxe?mac=${net0/mac}

# TFTP Service
enable-tftp
tftp-root=%s

# Logging
log-facility=%s/dnsmasq.log
log-dhcp
log-async=25
`, time.Now().UTC().Format(time.RFC3339),
		m.cfg.Interface,
		dhcpRangeSection,
		arm64BootLine,
		serverIP, m.cfg.HTTPPort,
		m.cfg.TFTPDir,
		m.cfg.LogDir,
	)

	confPath := filepath.Join(m.cfg.ConfDir, "dnsmasq.conf")
	if err := os.WriteFile(confPath, []byte(confContent), 0644); err != nil {
		return fmt.Errorf("failed to write dnsmasq.conf: %w", err)
	}

	slog.InfoContext(ctx, "rendered dnsmasq configuration", "path", confPath, "interface", m.cfg.Interface, "ip", serverIP)
	return nil
}

// Start launches the supervised dnsmasq process.
func (m *Manager) Start(ctx context.Context) error {
	m.mu.Lock()
	if m.running {
		m.mu.Unlock()
		return nil
	}

	// Verify dnsmasq binary exists in PATH
	binaryPath, err := exec.LookPath("dnsmasq")
	if err != nil {
		m.mu.Unlock()
		slog.WarnContext(ctx, "dnsmasq binary not found in PATH; network boot supervision disabled", "error", err)
		return nil
	}

	confPath := filepath.Join(m.cfg.ConfDir, "dnsmasq.conf")
	m.mu.Unlock()

	if err := m.RenderConfig(ctx); err != nil {
		return err
	}

	m.mu.Lock()
	defer m.mu.Unlock()

	if m.running {
		return nil
	}

	procCtx, cancel := context.WithCancel(context.Background())
	m.cancel = cancel

	cmd := exec.CommandContext(procCtx, binaryPath, "-k", "-C", confPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Start(); err != nil {
		cancel()
		return fmt.Errorf("failed to start dnsmasq: %w", err)
	}

	m.cmd = cmd
	m.running = true
	exitCh := make(chan struct{})
	m.exitCh = exitCh

	// Monitor child process asynchronously
	go func() {
		err := cmd.Wait()
		m.mu.Lock()
		m.running = false
		m.mu.Unlock()
		close(exitCh)
		if err != nil && procCtx.Err() == nil {
			slog.Error("dnsmasq child process exited unexpectedly", "error", err)
		}
	}()

	slog.InfoContext(ctx, "dnsmasq process supervisor started", "pid", cmd.Process.Pid)
	return nil
}

// Stop gracefully shuts down the child process.
func (m *Manager) Stop(ctx context.Context) error {
	m.mu.Lock()
	if !m.running || m.cmd == nil || m.cmd.Process == nil {
		m.mu.Unlock()
		return nil
	}

	m.running = false
	cmd := m.cmd
	exitCh := m.exitCh
	cancel := m.cancel
	slog.InfoContext(ctx, "stopping dnsmasq process", "pid", cmd.Process.Pid)
	m.mu.Unlock()

	if cancel != nil {
		cancel()
	}

	// Signal SIGTERM for clean shutdown
	_ = cmd.Process.Signal(syscall.SIGTERM)

	select {
	case <-exitCh:
		// Cleanly terminated
	case <-time.After(2 * time.Second):
		_ = cmd.Process.Kill()
		select {
		case <-exitCh:
		case <-time.After(500 * time.Millisecond):
		}
	case <-ctx.Done():
		_ = cmd.Process.Kill()
		return ctx.Err()
	}

	m.mu.Lock()
	m.running = false
	m.mu.Unlock()
	return nil
}

// Reload re-renders configuration and cleanly restarts dnsmasq to rebind network interfaces and DHCP pools.
func (m *Manager) Reload(ctx context.Context) error {
	m.mu.Lock()
	wasRunning := m.running
	m.mu.Unlock()

	if err := m.RenderConfig(ctx); err != nil {
		return fmt.Errorf("failed re-rendering dnsmasq configuration during reload: %w", err)
	}

	if !wasRunning {
		return m.Start(ctx)
	}

	slog.InfoContext(ctx, "restarting dnsmasq process to apply updated network parameters")
	stopCtx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	if err := m.Stop(stopCtx); err != nil {
		slog.WarnContext(ctx, "error stopping dnsmasq before restart", "error", err)
	}

	return m.Start(ctx)
}

// UpdateNetworkSettings updates the active DHCP/PXE configuration parameters and restarts the service.
func (m *Manager) UpdateNetworkSettings(ctx context.Context, netCfg domain.NetworkSettings, iface string) error {
	m.mu.Lock()
	if iface != "" {
		m.cfg.Interface = iface
	}
	m.cfg.SubnetCIDR = netCfg.SubnetCIDR
	m.cfg.DHCPRangeStart = netCfg.DHCPRangeStart
	m.cfg.DHCPRangeEnd = netCfg.DHCPRangeEnd
	m.cfg.Gateway = netCfg.Gateway
	m.cfg.DNSServers = netCfg.DNSServers
	m.cfg.LeaseDurationMinutes = netCfg.LeaseDurationMinutes
	m.mu.Unlock()

	slog.InfoContext(ctx, "updated dnsmasq network settings",
		"interface", m.cfg.Interface,
		"subnet", m.cfg.SubnetCIDR,
		"range_start", m.cfg.DHCPRangeStart,
		"range_end", m.cfg.DHCPRangeEnd,
	)

	return m.Reload(ctx)
}

func (m *Manager) detectInterfaceIP(ifaceName string) string {
	iface, err := net.InterfaceByName(ifaceName)
	if err != nil {
		return ""
	}
	addrs, err := iface.Addrs()
	if err != nil {
		return ""
	}
	for _, addr := range addrs {
		if ipNet, ok := addr.(*net.IPNet); ok && !ipNet.IP.IsLoopback() {
			if ipNet.IP.To4() != nil {
				return ipNet.IP.String()
			}
		}
	}
	return ""
}

func (m *Manager) seedTFTPBootloaders(ctx context.Context) {
	requiredFiles := []string{"ipxe.efi", "undionly.kpxe", "ipxe-arm64.efi"}
	searchDirs := []string{
		"assets/tftp",
		"/usr/share/redwolf/assets/tftp",
		"data/tftp",
		"../assets/tftp",
	}

	for _, reqFile := range requiredFiles {
		targetPath := filepath.Join(m.cfg.TFTPDir, reqFile)
		if _, err := os.Stat(targetPath); err == nil {
			continue // Already exists
		}

		for _, srcDir := range searchDirs {
			srcPath := filepath.Join(srcDir, reqFile)
			if data, err := os.ReadFile(srcPath); err == nil {
				if err := os.WriteFile(targetPath, data, 0644); err == nil {
					slog.InfoContext(ctx, "seeded tftp bootstrap loader", "file", reqFile, "source", srcPath, "target", targetPath)
					break
				}
			}
		}
	}
}
